#include <QCoreApplication>
#include <QDir>
#include <QDebug>
#include <QFile>
#include <QTextStream>

int main(int argc, char *argv[])
{
    QCoreApplication a(argc, argv);
    QString dirname = "D:/NOC/Tugas Padli/Produktif/Belajar C++/tes_QDir";
    QDir file(dirname);
    if(!file.exists()){
        qDebug()<<"Directory is success to added";
        file.mkpath(dirname);
        QFile file("insert.txt");
        if(file.open(QIODevice::WriteOnly | QIODevice::Text)){
            QTextStream output(&file);
            output<<"This file is generated by QT";
            file.close();
            return 0;
        }else{
            qDebug()<<"File failed to create !";
        }
    }else{
        qDebug()<<"Directory already exist";
        QFile file("exist.txt");
        if(file.open(QIODevice::WriteOnly | QIODevice::Text)){
            QTextStream output(&file);
            output<<"This file is generated by QT";
            file.close();
            return 0;
        }else{
            qDebug()<<"File failed to create !";
        }
    }
    return a.exec();
}
